### ISSUE TITLE
Birds fly even sleeping

### ISSUE THREAD

**Issue by Shatter0Ice** [ikerleon02/TheBirdwatchingMod#1]
When next to a feeder, at night time, birds attracted to it fly with the sleeping animation.

![2019-09-21_18 47 49](https://user-images.githubusercontent.com/55634019/65377160-7d811380-dca0-11e9-9d4b-1f1f240d99d2.png)

**Comment by JoelZBub** [comment]
If this is fixed in development version, it should be labeled "Fixed in dev " when it's closed.
