### ISSUE TITLE
Request of updating to 1.16.4 for Fabric

### ISSUE THREAD

**Issue by linzexin022** [ikerleon02/TheBirdwatchingMod#10]
Hi there! I love your idea on birds and these birds are so beautiful and I want to add them to my 1.16.4 world. However, this mod cannot run at 1.16.4 on Fabric which makes me upset... I'd appreciate it if you could make a 1.16.4 version!

**Comment by MLGMagicHoodini** [comment]
Afaik 1.16.1 mods should work on 1.16+ but not sure if it's same for Fabric, but still updating this mod to 1.16.4 ain't that simple is not just changing a number it may need some code changes too that take time

**Comment by K0-RR** [comment]
@ikerleon02 what's invalid in this issue? Is this mod not developed anymore?

**Comment by ikerleon02** [comment]
> @ikerleon02 what's invalid in this issue? Is this mod not developed anymore?

Because it isn't an issue, it is a port request
