### ISSUE TITLE
Birds permanently asleep in my worlds

### ISSUE THREAD

**Issue by viceroy369** [ikerleon02/TheBirdwatchingMod#2]
The birds are always constantly asleep after the first 12000 ticks in my worlds even during the day time. To reproduce I just go /time set 24000 or more and get permanently sleeping birds.

**Comment by viceroy369** [comment]
Ok I tried with nothing but Birdwatching mod and this still appears to be the case so it's not a mod conflict. The birds fall asleep on the first night and never ever wake up. Forge 14.23.5.2847

**Comment by ikerleon02** [comment]
I'll fix it in the next update, thanks for dedicate some time to test it and write the report!

**Comment by viceroy369** [comment]
Thanks! Great mod apart from this bug btw!
