### ISSUE TITLE
bird of paridise is invisible

### ISSUE THREAD

**Issue by Tobiasspet** [ikerleon02/TheBirdwatchingMod#4]
Hi just downloaded your mod its awesome but when i spawned in the bird of paridise i only got a little shadow the rest of the birds spawn except for this one
![Screen Shot 2020-03-25 at 17 38 24](https://user-images.githubusercontent.com/62662899/77561794-780abd00-6ebf-11ea-9b98-ab60e012f656.png)

**Comment by ikerleon02** [comment]
Thanks for reporting it! It has been fixed in dev versions. Soon you'll have a new release with a few new birds and this bug fixed.
