### ISSUE TITLE
Binoculars zoom

### ISSUE THREAD

**Issue by HeroMeDavid** [ikerleon02/TheBirdwatchingMod#5]
Its not a gamebreaking mod or anything but if you use the binoculars and you press Q to drop the item you will still be zoomed in until you pick up the item again and press right click again.

**Comment by ikerleon02** [comment]
thanks for reporting it, i'll ficx it in the next version if i can

**Comment by HeroMeDavid** [comment]
I just tried to recreate it but I can't. It doesn't stay zoomed in but the outline around the screen does stay.

**Comment by ikerleon02** [comment]
I'll try to recreate it, but if it is only that, it is pretty easy to fix
